### ISSUE TITLE
Support Ogg "Remastered" music from Cave Story+ once SDL_mixer is used

### ISSUE THREAD

**Issue by ssokolow** [isage/nxengine-evo#15]
I know that supporting Cave Story+ wholesale isn't a goal but, once you check off "rewrite soundlib to use SDL_mixer", might you be willing to support the "Remastered" music option from Cave Story+?

Despite the original NXEngine having been packaged for my [OpenPandora](http://openpandora.org/) (ARM+Xfce palmtop PC), I've never been able to feel comfortable playing Cave Story on the go because I could never get comfortable with the "early SNES-era graphics with NES-era music" feel I got from it. (Using Cave Story+ with original SNES-like graphics, the remastered SNES-like music, and Antimicro to map my USB controller adapter fixes that for play at home.)

Given that SDL_mixer has support for Ogg Vorbis on the music channel if it manages to `dlopen` the relevant libraries, I'm hoping you wouldn't find it too onerous to include a lookup table for the `data/base/Ogg11/*_intro.ogg` and `data/base/Ogg11/*_loop.ogg` files from Cave Story+ and some method of enabling their use. (Even just a hard-coded "If they're present, they're enabled" would satisfy me.)

Splicing them should be just a matter of calling `Mix_LoadMUS` for both pieces of the song before you start playing anything and then using `Mix_HookMusicFinished` to trigger looping playback of the `*_loop.ogg` file when non-looping playback of the `*_intro.ogg` file completes.

(Heck, if that proves to be problematic, I wouldn't mind [producing](http://blog.ssokolow.com/archives/2014/03/13/working-around-the-cave-story-soundtrack/) spliced and/or transcoded files to feed to it if that's what it takes... or, for that matter, settling for an audible glitch at the transition point between the intro and loop parts.)

**Comment by treaki** [comment]
only that cavestory+ has a horrible english translation that is based on the original fan translation from the Japanese language but has been made bad on purpose to hide that the fan translation is used and being able to claim to have translated it on there own. Only bad that they had forgotten to remove the comments so there swindle come out afterwards... i mean how the fuck can you ever come up with bushland for grasstown (only as an example)??

**Comment by ssokolow** [comment]
Good to know, but, not really a compelling option because:

1. For better or for worse, I didn't have a Nintendo console until my grandmother bought me a SNES one Christmas, so I can't help but see the combination of classic SNES-like Cave Story graphics and classic NES-like Cave Story music as dissonant and grating.

    (I still enjoy NES-inspired games, but having graphics beyond what an NES is capable of is too strong a reminder that I could be listening to something with better synth.)

2. It's been over half a decade since I got my copy of Cave Story+ as part of the Humble Indie Bundle 

If nxengine-evo supports the SNES-like "Remastered" music, then I can merge that into the fan-translated version and play that. Otherwise, I'll stick to my copy of Cave Story+.

(And it'd be nice to play it on my OpenPandora handheld... which is a non-Android ARM Linux device, so nxengine-evo with Remastered music support is my only option there.)

**Comment by isage** [comment]
Good news: nxengine-evo now supports ogg music.
Not so good news: only "New" music from CS+ is supported (copy ogg folder to data and enable in options)
I'm working on support for "Remastered" music. Shouldn't be too hard to implement.

**Comment by isage** [comment]
@ssokolow also, can you tell where and how wanpaku_ending_*.ogg and lastcave2_*.ogg used?

**Comment by ssokolow** [comment]
Unfortunately, I can't. I've been so busy over the last few months that my memories of Cave Story+ are hazy at best.

(Heck, I still have barely-started copies of Undertale, Owlboy, and the A Boy and His Blob remake sitting on my hard drive because, when I *did* find leisure time at home, I was more in the mood for either reading or programming.)

**Comment by isage** [comment]
Okay, so. "Remastered" music is supported since 49b6175ae374fa4310d5c85269e7c6411288b0da
Just copy Ogg11 to data (keeping letter case) and select "Remastered" for tracks in options.
There are two caveats:   
1. SDL_mixer docs state the we should never-ever call it's functions from MusicFinished callback, but i still do. Because if i restart music inside main thread there's noticeable pause in music.
2. There's currently no support for two additional tracks (wanpaku_ending and lastcave2).

I'll do a proper release later and 'll keep this issue open for now (until i fugure out how stable it is and where those two tracks are used).

**Comment by Clownacy** [comment]
> @ssokolow also, can you tell where and how wanpaku_ending.ogg and lastcave2.ogg used?
I've been told that wanpaku_ending.ogg is used for the credits, replacing the original wanpaku.ogg, and lastcave2.ogg is used in Last Cave if you reach without ever dying or saving. Supposedly, this is how they were used in Cave Story 3D, but I've never beaten that game. I don't think either of these were backported properly to Cave Story+ PC, either, so you'll never hear them there.

**Comment by ssokolow** [comment]
Ahh. That'd explain why I don't recognize them. Even if I were the type to go for that degree of completion when playing a game (100% *with* saving and plenty of deaths is good enough for me, thanks), I don't have enough contiguous leisure time to marathon a game.

**Comment by Clownacy** [comment]
Oh right, I should probably also mention that the Switch port of Cave Story+ added an extra soundtrack, called "Famitracks". It uses the same setup as the Remastered one (split into '_intro' and '_loop' files), and is stored in a folder called "ogg17" (all the folders in that port are lowercase, for some reason). Unlike the Remastered soundtrack, however, Famitracks is 44100Hz instead of 22050Hz. It also doesn't have any wanpaku_ending.ogg or lastcave2.ogg files.

[I created a list of each song and its properties for my freeware Cave Story ogg mod a while ago, which might help.](https://github.com/Clownacy/Cave-Story-Mod-Loader/blob/master/bin/mods/ogg_music/Cave%20Story%20Famitracks/playlist.txt)

I heard an update added yet another soundtrack, but I haven't got around to looking at it.

**Comment by isage** [comment]
Okay. so.
1) I'm not sure it's worth it to support wanpaku_ending.ogg and lastcave2.ogg
2) If there's no legal way to obtain "Famitracks", i'm not sure it's worth supporting those either. I'll think about it if they ever make their way to pc port.

**Comment by isage** [comment]
Closing for now.
